apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-permissao-imagens
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-permissao-sessoes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set-noticia
spec:
  serviceName: stateful-set-noticia
  selector:
    matchLabels:
      name: stateful-set-pod-noticia
  template:
    metadata:
      labels:
        name: stateful-set-pod-noticia
    spec:
      containers:
        - name: container-stateful-set-noticias
          image: gsilveira/noticias
          #O imagePullPolicy com o valor Never é para que seja possível utilizar as imagens locais
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 400m
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set-sistema
spec:
  serviceName: stateful-set-sistema
  selector:
    matchLabels:
      name: stateful-set-pod-sistema
  template:
    metadata:
      labels:
        name: stateful-set-pod-sistema
    spec:
      containers:
        - name: container-stateful-set-pod-sistema
          image: gsilveira/sistema
          #O imagePullPolicy com o valor Never é para que seja possível utilizar as imagens locais
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command: ["sh", "enviar-mensagem.sh"]
          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessoes
              mountPath: /tmp
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: persistent-volume-permissao-imagens
        - name: sessoes
          persistentVolumeClaim:
            claimName: persistent-volume-permissao-sessoes
---
apiVersion: v1
kind: Service
metadata:
  name: service-stateful-set-noticia
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 31000
  selector:
    name: stateful-set-pod-noticia
---
apiVersion: v1
kind: Service
metadata:
  name: service-stateful-set-sistema
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30500
  selector:
    name: stateful-set-pod-sistema