apiVersion: v1
kind: Service
metadata:
  name: service-stateful-set-sistema
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30500
  selector:
    name: stateful-set-pod-sistema
