apiVersion: v1
kind: Service
metadata:
  name: service-stateful-set-noticia
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 31000
  selector:
    name: stateful-set-pod-noticia